/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function assembleEnvironment(env: EnvInput, references: Array<ReferenceInfo>): string

export declare function assembleMcpBlock(instructions: Array<McpInstruction>): string

export declare function assembleSkillsBlock(skills: Array<SkillInfo>, verbose: boolean): string

export declare function assembleSystemPrompt(agentPrompt: string | undefined | null, providerTemplate: string, envBlock: string, instructionBlock: Array<string>, skillsBlock: string, userSystem: string | undefined | null, jsonSchema: boolean): Array<string>

export interface EnvInput {
  modelId: string
  providerId: string
  directory: string
  worktree: string
  isGit: boolean
  platform: string
  date: string
}

export interface McpInstruction {
  name: string
  instructions: string
  tools: Array<string>
}

export interface ReferenceInfo {
  name: string
  path: string
  description?: string
}

export declare function selectProviderTemplate(modelId: string): string

export interface SkillInfo {
  name: string
  description?: string
  location: string
}
