/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Database {
  constructor(path: string)
  exec(sql: string, params: Array<any>): number
  queryAll(sql: string, params: Array<any>): Array<any>
  queryValues(sql: string, params: Array<any>): Array<Array<any>>
}
