/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function grepFiles(pattern: string, root: string, includePattern?: string | undefined | null, maxMatches?: number | undefined | null): Promise<Array<GrepMatch>>

export interface GrepMatch {
  path: string
  line: number
  column: number
  text: string
}
