/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function executeShell(options: ShellOptions): Promise<ShellOutput>

export interface FileContent {
  content: string
  size: number
}

export interface GlobEntry {
  path: string
  size: number
  isDir: boolean
}

export declare function globFiles(pattern: string, root: string): Array<GlobEntry>

export declare function grepFiles(pattern: string, root: string, includePattern?: string | undefined | null, maxMatches?: number | undefined | null): Promise<Array<GrepMatch>>

export interface GrepMatch {
  path: string
  line: number
  column: number
  text: string
}

export declare function readFile(path: string): Promise<FileContent>

export interface ShellOptions {
  command: string
  workdir?: string
  timeoutMs?: number
  env?: Array<[string, string]>
  maxOutputBytes?: number
}

export interface ShellOutput {
  stdout: string
  stderr: string
  exitCode: number
  timedOut: boolean
  signal?: string
}

export declare function writeFile(path: string, content: string): Promise<void>
