/* auto-generated by NAPI-RS */
export interface GrepMatch {
  path: string
  line: number
  column: number
  text: string
}

export declare function grepFiles(pattern: string, root: string, includePattern?: string, maxMatches?: number): Promise<GrepMatch[]>
