/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface SseEvent {
  data: string
  eventType?: string
  id?: string
}

export interface SseStreamOptions {
  url: string
  method: string
  headers: Array<[string, string]>
  body: string
  timeoutMs?: number
  maxRetries?: number
}

export declare function streamSse(options: SseStreamOptions, onEvent: SseCallback, onError: ErrorCallback, onDone: DoneCallback): Promise<void>
