/* auto-generated by NAPI-RS */
export interface SseEvent {
  data: string
  eventType?: string
  id?: string
}

export interface SseStreamOptions {
  url: string
  method: string
  headers: Array<[string, string]>
  body: string
  timeoutMs?: number
  maxRetries?: number
}

export declare function streamSse(
  options: SseStreamOptions,
  onEvent: (err: unknown, event: SseEvent) => void,
  onError: (err: unknown, msg: string) => void,
  onDone: (err: unknown) => void,
): Promise<void>
