/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function countTokens(text: string, model?: string | undefined | null): number

export declare function countTokensEstimate(text: string): number

export declare function hello(): string
