name: Native Modules

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  typecheck:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bun
      - name: Typecheck
        run: bun run typecheck

  lint:
    # 代码风格检查
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bun
      - name: Lint
        run: bun run lint
